// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/EditorialSplit.tsx": () => import("../components/mockups/hero-variants/EditorialSplit.tsx"),
  "./components/mockups/hero-variants/LiveMarketplace.tsx": () => import("../components/mockups/hero-variants/LiveMarketplace.tsx"),
  "./components/mockups/hero-variants/SpatialImmersion.tsx": () => import("../components/mockups/hero-variants/SpatialImmersion.tsx"),
  "./components/mockups/hero-variants/UtilityFirst.tsx": () => import("../components/mockups/hero-variants/UtilityFirst.tsx")
};
